import { vi } from "vitest";
import type { RepoConfig } from "../../src/lib/types";

export const defaultMockConfig: RepoConfig = {
  version: 1,
  defaultModel: "claude-sonnet-4-20250514",
  autoCommit: true,
  commitPrefix: "promptcase: ",
  commitDelayMs: 5000,
  tokenCountModels: ["gpt-4", "claude-sonnet-4-20250514"],
  lintRules: {},
  editorFontFamily: "Fira Code",
  editorFontSize: 14,
  editorWordWrap: true,
  editorLineNumbers: true,
  editorShowInvisibles: false,
  theme: "dark",
  sidebarPosition: "left",
  keybindings: {},
  savedFilters: [],
};

export function createMockApi(overrides: Record<string, unknown> = {}) {
  return {
    listTags: vi.fn().mockResolvedValue([]),
    renameTag: vi.fn().mockResolvedValue(0),
    deleteTag: vi.fn().mockResolvedValue(0),
    mergeTags: vi.fn().mockResolvedValue(0),
    listFiles: vi.fn().mockResolvedValue([]),
    listFolders: vi.fn().mockResolvedValue([]),
    readFile: vi.fn().mockResolvedValue({ path: "", frontmatter: {}, body: "", raw: "" }),
    writeFile: vi.fn().mockResolvedValue({ ok: true }),
    createFile: vi.fn().mockResolvedValue({ path: "", frontmatter: {}, body: "", raw: "" }),
    deleteFile: vi.fn().mockResolvedValue({ ok: true }),
    moveFile: vi.fn().mockResolvedValue({ ok: true }),
    createFolder: vi.fn().mockResolvedValue({ ok: true }),
    renameFolder: vi.fn().mockResolvedValue({ ok: true }),
    deleteFolder: vi.fn().mockResolvedValue({ ok: true }),
    duplicateFile: vi.fn().mockResolvedValue({ path: "", frontmatter: {}, body: "", raw: "" }),
    moveFiles: vi.fn().mockResolvedValue({ ok: true }),
    gitLog: vi.fn().mockResolvedValue([]),
    gitDiff: vi.fn().mockResolvedValue({ raw: "", hunks: [] }),
    gitRestore: vi.fn().mockResolvedValue(null),
    gitShowFile: vi.fn().mockResolvedValue(""),
    gitStatus: vi.fn().mockResolvedValue({ initialized: true, clean: true, totalFiles: 0, repoPath: "" }),
    resolveTemplate: vi.fn().mockResolvedValue({ text: "", variables: {}, unresolvedVariables: [], includedFragments: [] }),
    lintFile: vi.fn().mockResolvedValue([]),
    lintAll: vi.fn().mockResolvedValue({}),
    getVariables: vi.fn().mockResolvedValue([]),
    countTokens: vi.fn().mockResolvedValue(0),
    countTokensResolved: vi.fn().mockResolvedValue(0),
    search: vi.fn().mockResolvedValue([]),
    reindex: vi.fn().mockResolvedValue({ ok: true }),
    getConfig: vi.fn().mockResolvedValue({ ...defaultMockConfig }),
    updateConfig: vi.fn().mockResolvedValue({ ...defaultMockConfig }),
    generateCommitMessage: vi.fn().mockResolvedValue("auto-commit"),
    commitFile: vi.fn().mockResolvedValue({ ok: true }),
    getApiKey: vi.fn().mockResolvedValue(null),
    setApiKey: vi.fn().mockResolvedValue({ ok: true }),
    deleteApiKey: vi.fn().mockResolvedValue({ ok: true }),
    runPrompt: vi.fn().mockResolvedValue({ ok: true }),
    cancelPrompt: vi.fn().mockResolvedValue({ ok: true }),
    runEval: vi.fn().mockResolvedValue({ ok: true }),
    startWatcher: vi.fn().mockResolvedValue({ ok: true }),
    stopWatcher: vi.fn().mockResolvedValue({ ok: true }),
    markFileWriting: vi.fn().mockResolvedValue({ ok: true }),
    unmarkFileWriting: vi.fn().mockResolvedValue({ ok: true }),
    exportFileClipboard: vi.fn().mockResolvedValue(""),
    exportFolderZip: vi.fn().mockResolvedValue([]),
    importFiles: vi.fn().mockResolvedValue([]),
    importFromText: vi.fn().mockResolvedValue({ path: "", frontmatter: {}, body: "", raw: "" }),
    installSamples: vi.fn().mockResolvedValue(""),
    saveRecovery: vi.fn().mockResolvedValue({ ok: true }),
    clearRecovery: vi.fn().mockResolvedValue({ ok: true }),
    loadRecovery: vi.fn().mockResolvedValue([]),
    clearAllRecovery: vi.fn().mockResolvedValue({ ok: true }),
    scanDirectory: vi.fn().mockResolvedValue([]),
    ...overrides,
  };
}

export function mockIpcModule(mockApi: ReturnType<typeof createMockApi>) {
  return {
    api: mockApi,
    isTauri: vi.fn().mockReturnValue(false),
  };
}
